name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - uses: php-actions/composer@v5

  phpunit:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: PHP Unit tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0
          php_extensions: xdebug
          configuration: test/phpunit/phpunit.xml
          bootstrap: vendor/autoload.php

  phpstan:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: PHP Static Analysis
        uses: php-actions/phpstan@v2
        with:
          path: src/

  codestyle:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: PHP Codestyle Fixer
        uses: php-actions/composer@v5
        with:
          command: run test:codestyle
